export const adStructureStyles = {
  wrapper: {
    display: "flex",
    minHeight: "100vh",
    backgroundColor: "#f5f0f0",
  },
  mainContent: {
    marginLeft: "250px",
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  pageContent: {
    padding: "25px",
    flex: 1,
  },
  pageTitleRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "25px",
  },
  pageTitle: {
    fontSize: "22px",
    fontWeight: "700",
    color: "#2c3e50",
    marginBottom: "5px",
  },
  pageSubtitle: {
    color: "#7f8c8d",
    fontSize: "14px",
    marginBottom: "0",
  },
  // Tabs
  tabsRow: {
    display: "flex",
    gap: "5px",
    marginBottom: "25px",
    borderBottom: "2px solid #f0f0f0",
  },
  tab: {
    padding: "10px 20px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
    color: "#7f8c8d",
    borderBottom: "2px solid transparent",
    marginBottom: "-2px",
    transition: "all 0.2s",
  },
  tabActive: {
    padding: "10px 20px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
    color: "#3498db",
    borderBottom: "2px solid #3498db",
    marginBottom: "-2px",
  },
  // Cards grid
  cardsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(250px, 1fr))",
    gap: "15px",
    width: "100%",
  },
  card: {
    backgroundColor: "white",
    borderRadius: "12px",
    padding: "20px",
    boxShadow: "0 2px 10px rgba(0,0,0,0.06)",
    cursor: "pointer",
    transition: "all 0.2s",
    border: "2px solid transparent",
  },
  cardActive: {
    backgroundColor: "white",
    borderRadius: "12px",
    padding: "20px",
    boxShadow: "0 4px 15px rgba(52,152,219,0.2)",
    cursor: "pointer",
    border: "2px solid #3498db",
  },
  cardName: {
    fontSize: "15px",
    fontWeight: "700",
    color: "#2c3e50",
    marginBottom: "5px",
  },
  cardDesc: {
    fontSize: "12px",
    color: "#7f8c8d",
    marginBottom: "10px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  cardBadge: {
    display: "inline-block",
    padding: "3px 10px",
    borderRadius: "20px",
    fontSize: "12px",
    fontWeight: "600",
    backgroundColor: "#ebf5fb",
    color: "#2980b9",
  },
  // Members panel
  membersPanel: {
    backgroundColor: "white",
    borderRadius: "12px",
    boxShadow: "0 2px 10px rgba(0,0,0,0.08)",
    overflow: "hidden",
  },
  membersPanelHeader: {
    padding: "20px 25px",
    borderBottom: "1px solid #f0f0f0",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  membersPanelTitle: {
    fontSize: "16px",
    fontWeight: "600",
    color: "#2c3e50",
  },
  addBtn: {
    background: "linear-gradient(135deg, #3498db, #2980b9)",
    border: "none",
    borderRadius: "8px",
    padding: "8px 16px",
    color: "white",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
  },
  createBtn: {
    background: "linear-gradient(135deg, #2ecc71, #27ae60)",
    border: "none",
    borderRadius: "8px",
    padding: "8px 16px",
    color: "white",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
  },
  memberRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "12px 25px",
    borderBottom: "1px solid #f8f8f8",
  },
  memberName: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#2c3e50",
  },
  removeBtn: {
    padding: "4px 12px",
    borderRadius: "6px",
    border: "none",
    backgroundColor: "#fdecea",
    color: "#e74c3c",
    fontSize: "12px",
    fontWeight: "600",
    cursor: "pointer",
  },
  emptyState: {
    textAlign: "center",
    padding: "40px",
    color: "#7f8c8d",
    fontSize: "14px",
  },
  footer: {
    textAlign: "center",
    padding: "15px",
    color: "#95a5a6",
    fontSize: "13px",
    borderTop: "1px solid #f0f0f0",
    backgroundColor: "white",
  },
  // Modal
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 9999,
  },
  modalCard: {
    backgroundColor: "white",
    borderRadius: "12px",
    padding: "30px",
    width: "100%",
    maxWidth: "420px",
    boxShadow: "0 20px 60px rgba(0,0,0,0.3)",
  },
  modalTitle: {
    fontSize: "18px",
    fontWeight: "700",
    color: "#2c3e50",
    marginBottom: "5px",
  },
  modalSubtitle: {
    color: "#7f8c8d",
    fontSize: "13px",
    marginBottom: "20px",
  },
  modalLabel: {
    fontWeight: "600",
    color: "#2c3e50",
    fontSize: "14px",
    marginBottom: "5px",
    display: "block",
  },
  modalInput: {
    width: "100%",
    padding: "10px 15px",
    border: "1px solid #ddd",
    borderRadius: "8px",
    fontSize: "14px",
    marginBottom: "15px",
    outline: "none",
  },
  modalSelect: {
    width: "100%",
    padding: "10px 15px",
    border: "1px solid #ddd",
    borderRadius: "8px",
    fontSize: "14px",
    marginBottom: "15px",
    outline: "none",
    backgroundColor: "white",
  },
  modalFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "10px",
    marginTop: "10px",
  },
  cancelBtn: {
    padding: "9px 20px",
    borderRadius: "8px",
    border: "1px solid #ddd",
    background: "white",
    color: "#7f8c8d",
    cursor: "pointer",
    fontSize: "14px",
  },
  submitBtn: {
    padding: "9px 20px",
    borderRadius: "8px",
    border: "none",
    background: "linear-gradient(135deg, #3498db, #2980b9)",
    color: "white",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
  },
};
