export const auditLogsStyles = {
  wrapper: {
    display: "flex",
    minHeight: "100vh",
    backgroundColor: "#f0f2f5",
  },
  mainContent: {
    marginLeft: "250px",
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  pageContent: {
    padding: "25px",
    flex: 1,
  },
  pageTitleRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "25px",
  },
  pageTitle: {
    fontSize: "22px",
    fontWeight: "700",
    color: "#2c3e50",
    marginBottom: "5px",
  },
  pageSubtitle: {
    color: "#7f8c8d",
    fontSize: "14px",
    marginBottom: "0",
  },
  filtersRow: {
    display: "flex",
    gap: "10px",
    marginBottom: "20px",
    flexWrap: "wrap",
  },
  filterSelect: {
    padding: "8px 15px",
    border: "1px solid #ddd",
    borderRadius: "8px",
    fontSize: "14px",
    outline: "none",
    backgroundColor: "white",
    cursor: "pointer",
    minWidth: "150px",
  },
  filterInput: {
    padding: "8px 15px",
    border: "1px solid #ddd",
    borderRadius: "8px",
    fontSize: "14px",
    outline: "none",
    minWidth: "200px",
  },
  clearBtn: {
    padding: "8px 15px",
    border: "1px solid #ddd",
    borderRadius: "8px",
    fontSize: "14px",
    backgroundColor: "white",
    cursor: "pointer",
    color: "#7f8c8d",
  },
  tableCard: {
    backgroundColor: "white",
    borderRadius: "12px",
    boxShadow: "0 2px 10px rgba(0,0,0,0.08)",
    overflow: "hidden",
  },
  tableHeader: {
    padding: "20px 25px",
    borderBottom: "1px solid #f0f0f0",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  tableTitle: {
    fontSize: "16px",
    fontWeight: "600",
    color: "#2c3e50",
  },
  tableHead: { backgroundColor: "#f8f9fa" },
  th: {
    padding: "12px 20px",
    fontSize: "13px",
    fontWeight: "600",
    color: "#7f8c8d",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  td: {
    padding: "12px 20px",
    fontSize: "13px",
    color: "#2c3e50",
    verticalAlign: "middle",
  },
  badge: {
    padding: "3px 10px",
    borderRadius: "20px",
    fontSize: "11px",
    fontWeight: "600",
  },
  badgeSuccess: { backgroundColor: "#eafaf1", color: "#27ae60" },
  badgeFailed: { backgroundColor: "#fdecea", color: "#e74c3c" },
  actionBadge: {
    padding: "3px 10px",
    borderRadius: "6px",
    fontSize: "11px",
    fontWeight: "600",
  },
  actionLogin: { backgroundColor: "#ebf5fb", color: "#2980b9" },
  actionCreate: { backgroundColor: "#eafaf1", color: "#27ae60" },
  actionEdit: { backgroundColor: "#fef9e7", color: "#d35400" },
  actionDelete: { backgroundColor: "#fdecea", color: "#e74c3c" },
  actionDisable: { backgroundColor: "#fdecea", color: "#e74c3c" },
  actionEnable: { backgroundColor: "#eafaf1", color: "#27ae60" },
  pagination: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "10px",
    padding: "20px",
    borderTop: "1px solid #f0f0f0",
  },
  pageBtn: {
    padding: "6px 14px",
    borderRadius: "6px",
    border: "1px solid #ddd",
    backgroundColor: "white",
    cursor: "pointer",
    fontSize: "14px",
    color: "#2c3e50",
  },
  pageBtnActive: {
    padding: "6px 14px",
    borderRadius: "6px",
    border: "none",
    backgroundColor: "#3498db",
    cursor: "pointer",
    fontSize: "14px",
    color: "white",
    fontWeight: "600",
  },
  footer: {
    textAlign: "center",
    padding: "15px",
    color: "#95a5a6",
    fontSize: "13px",
    borderTop: "1px solid #f0f0f0",
    backgroundColor: "white",
  },
};
