export const dbUsersStyles = {
  wrapper: {
    display: "flex",
    minHeight: "100vh",
    backgroundColor: "#f0f2f5",
  },
  mainContent: {
    marginLeft: "250px",
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  pageContent: {
    padding: "25px",
    flex: 1,
  },
  pageTitleRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "25px",
  },
  pageTitle: {
    fontSize: "22px",
    fontWeight: "700",
    color: "#2c3e50",
    marginBottom: "5px",
  },
  pageSubtitle: {
    color: "#7f8c8d",
    fontSize: "14px",
    marginBottom: "0",
  },
  addBtn: {
    background: "linear-gradient(135deg, #2ecc71, #27ae60)",
    border: "none",
    borderRadius: "8px",
    padding: "10px 20px",
    color: "white",
    fontSize: "14px",
    fontWeight: "600",
    cursor: "pointer",
  },
  tableCard: {
    backgroundColor: "white",
    borderRadius: "12px",
    boxShadow: "0 2px 10px rgba(0,0,0,0.08)",
    overflow: "hidden",
  },
  tableHeader: {
    padding: "20px 25px",
    borderBottom: "1px solid #f0f0f0",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  tableTitle: {
    fontSize: "16px",
    fontWeight: "600",
    color: "#2c3e50",
  },
  searchInput: {
    padding: "8px 15px",
    border: "1px solid #ddd",
    borderRadius: "8px",
    fontSize: "14px",
    width: "250px",
    outline: "none",
  },
  tableHead: {
    backgroundColor: "#f8f9fa",
  },
  th: {
    padding: "12px 20px",
    fontSize: "13px",
    fontWeight: "600",
    color: "#7f8c8d",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  td: {
    padding: "14px 20px",
    fontSize: "14px",
    color: "#2c3e50",
    verticalAlign: "middle",
  },
  badge: {
    padding: "4px 10px",
    borderRadius: "20px",
    fontSize: "12px",
    fontWeight: "600",
  },
  badgeAdmin: {
    backgroundColor: "#ebf5fb",
    color: "#2980b9",
  },
  badgeUser: {
    backgroundColor: "#eafaf1",
    color: "#27ae60",
  },
  badgeActive: {
    backgroundColor: "#eafaf1",
    color: "#27ae60",
  },
  badgeInactive: {
    backgroundColor: "#fdecea",
    color: "#e74c3c",
  },
  actionBtn: {
    padding: "5px 12px",
    borderRadius: "6px",
    fontSize: "12px",
    fontWeight: "600",
    cursor: "pointer",
    border: "none",
    marginRight: "6px",
  },
  editBtn: {
    backgroundColor: "#ebf5fb",
    color: "#2980b9",
  },
  deleteBtn: {
    backgroundColor: "#fdecea",
    color: "#e74c3c",
  },
  footer: {
    textAlign: "center",
    padding: "15px",
    color: "#95a5a6",
    fontSize: "13px",
    borderTop: "1px solid #f0f0f0",
    backgroundColor: "white",
  },

  // Modal
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.5)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 9999,
  },
  modalCard: {
    backgroundColor: "white",
    borderRadius: "12px",
    padding: "30px",
    width: "100%",
    maxWidth: "450px",
    boxShadow: "0 20px 60px rgba(0,0,0,0.3)",
  },
  modalTitle: {
    fontSize: "18px",
    fontWeight: "700",
    color: "#2c3e50",
    marginBottom: "5px",
  },
  modalSubtitle: {
    color: "#7f8c8d",
    fontSize: "13px",
    marginBottom: "20px",
  },
  modalLabel: {
    fontWeight: "600",
    color: "#2c3e50",
    fontSize: "14px",
    marginBottom: "5px",
    display: "block",
  },
  modalInput: {
    width: "100%",
    padding: "10px 15px",
    border: "1px solid #ddd",
    borderRadius: "8px",
    fontSize: "14px",
    marginBottom: "15px",
    outline: "none",
  },
  modalSelect: {
    width: "100%",
    padding: "10px 15px",
    border: "1px solid #ddd",
    borderRadius: "8px",
    fontSize: "14px",
    marginBottom: "15px",
    outline: "none",
    backgroundColor: "white",
    cursor: "pointer",
  },
  modalFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "10px",
    marginTop: "10px",
  },
  cancelBtn: {
    padding: "9px 20px",
    borderRadius: "8px",
    border: "1px solid #ddd",
    background: "white",
    color: "#7f8c8d",
    cursor: "pointer",
    fontSize: "14px",
  },
  submitBtn: {
    padding: "9px 20px",
    borderRadius: "8px",
    border: "none",
    background: "linear-gradient(135deg, #2ecc71, #27ae60)",
    color: "white",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
  },
  deleteConfirmBtn: {
    padding: "9px 20px",
    borderRadius: "8px",
    border: "none",
    background: "linear-gradient(135deg, #e74c3c, #c0392b)",
    color: "white",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
  },
  divider: {
    borderTop: "1px solid #f0f0f0",
    margin: "15px 0",
  },
};
