export const loginStyles = {
  container: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "linear-gradient(135deg, #2c3e50, #3498db)",
  },
  card: {
    background: "white",
    borderRadius: "15px",
    padding: "40px",
    width: "100%",
    maxWidth: "400px",
    boxShadow: "0 20px 60px rgba(0,0,0,0.3)",
  },
  title: {
    fontWeight: "bold",
    color: "#2c3e50",
    marginBottom: "5px",
  },
  subtitle: {
    color: "#7f8c8d",
    marginBottom: "25px",
  },
  label: {
    fontWeight: "600",
    color: "#2c3e50",
    marginBottom: "5px",
  },
  input: {
    borderRadius: "8px",
    border: "1px solid #ddd",
    padding: "12px 15px",
    fontSize: "15px",
    width: "100%",
  },
  button: {
    background: "linear-gradient(135deg, #3498db, #2980b9)",
    border: "none",
    borderRadius: "8px",
    padding: "12px",
    color: "white",
    fontSize: "16px",
    fontWeight: "600",
    width: "100%",
    cursor: "pointer",
  },
  buttonDisabled: {
    background: "#bdc3c7",
    border: "none",
    borderRadius: "8px",
    padding: "12px",
    color: "white",
    fontSize: "16px",
    fontWeight: "600",
    width: "100%",
    cursor: "not-allowed",
  },
  errorAlert: {
    background: "#fdecea",
    border: "1px solid #e74c3c",
    borderRadius: "8px",
    padding: "12px",
    color: "#e74c3c",
    marginBottom: "15px",
  },
  helperText: {
    color: "#95a5a6",
    fontSize: "13px",
    textAlign: "center",
    marginTop: "15px",
  },
};
