export const navbarStyles = {
  navbar: {
    backgroundColor: "white",
    padding: "15px 25px",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    boxShadow: "0 2px 10px rgba(0,0,0,0.08)",
    position: "sticky",
    top: 0,
    zIndex: 999,
  },
  title: {
    fontSize: "18px",
    fontWeight: "600",
    color: "#2c3e50",
  },
  userSection: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    color: "#2c3e50",
  },
  avatar: {
    width: "35px",
    height: "35px",
    borderRadius: "50%",
    background: "linear-gradient(135deg, #3498db, #2980b9)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "white",
    fontWeight: "bold",
    fontSize: "14px",
  },
  username: {
    fontWeight: "600",
    fontSize: "14px",
  },
  role: {
    fontSize: "12px",
    color: "#7f8c8d",
  },
  logoutBtn: {
    background: "none",
    border: "1px solid #e74c3c",
    color: "#e74c3c",
    borderRadius: "6px",
    padding: "6px 14px",
    cursor: "pointer",
    fontSize: "13px",
    marginLeft: "15px",
  },
};
