export const profileStyles = {
  wrapper: {
    display: "flex",
    minHeight: "100vh",
    backgroundColor: "#f0f2f5",
  },
  mainContent: {
    marginLeft: "250px",
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  pageContent: {
    padding: "25px",
    flex: 1,
  },
  pageTitle: {
    fontSize: "22px",
    fontWeight: "700",
    color: "#2c3e50",
    marginBottom: "5px",
  },
  pageSubtitle: {
    color: "#7f8c8d",
    fontSize: "14px",
    marginBottom: "25px",
  },
  profileCard: {
    backgroundColor: "white",
    borderRadius: "12px",
    boxShadow: "0 2px 10px rgba(0,0,0,0.08)",
    overflow: "hidden",
    marginBottom: "25px",
  },
  profileHeader: {
    background: "linear-gradient(135deg, #2c3e50, #3498db)",
    padding: "40px",
    display: "flex",
    alignItems: "center",
    gap: "25px",
  },
  avatar: {
    width: "80px",
    height: "80px",
    borderRadius: "50%",
    background: "rgba(255,255,255,0.2)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "32px",
    fontWeight: "bold",
    color: "white",
    border: "3px solid rgba(255,255,255,0.5)",
  },
  profileName: {
    fontSize: "24px",
    fontWeight: "700",
    color: "white",
    marginBottom: "5px",
  },
  profileRole: {
    fontSize: "14px",
    color: "rgba(255,255,255,0.8)",
  },
  profileBody: {
    padding: "30px",
  },
  infoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "20px",
  },
  infoItem: {
    padding: "15px",
    backgroundColor: "#f8f9fa",
    borderRadius: "8px",
    borderLeft: "3px solid #3498db",
  },
  infoLabel: {
    fontSize: "12px",
    color: "#7f8c8d",
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    marginBottom: "5px",
  },
  infoValue: {
    fontSize: "15px",
    color: "#2c3e50",
    fontWeight: "600",
  },
  statsCard: {
    backgroundColor: "white",
    borderRadius: "12px",
    boxShadow: "0 2px 10px rgba(0,0,0,0.08)",
    padding: "25px",
  },
  statsTitle: {
    fontSize: "16px",
    fontWeight: "600",
    color: "#2c3e50",
    marginBottom: "20px",
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "15px",
  },
  statItem: {
    textAlign: "center",
    padding: "20px",
    borderRadius: "10px",
    background: "linear-gradient(135deg, #3498db, #2980b9)",
    color: "white",
  },
  statNumber: {
    fontSize: "28px",
    fontWeight: "bold",
    lineHeight: 1,
  },
  statLabel: {
    fontSize: "12px",
    opacity: 0.9,
    marginTop: "5px",
  },
  footer: {
    textAlign: "center",
    padding: "15px",
    color: "#95a5a6",
    fontSize: "13px",
    borderTop: "1px solid #f0f0f0",
    backgroundColor: "white",
  },
};
