export const sidebarStyles = {
  sidebar: {
    width: "250px",
    minHeight: "100vh",
    background: "linear-gradient(180deg, #2c3e50 0%, #34495e 100%)",
    color: "white",
    position: "fixed",
    top: 0,
    left: 0,
    zIndex: 1000,
    display: "flex",
    flexDirection: "column",
  },
  logo: {
    padding: "25px 20px",
    borderBottom: "1px solid rgba(255,255,255,0.1)",
    fontSize: "20px",
    fontWeight: "bold",
    color: "white",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  menu: {
    padding: "15px 0",
    flex: 1,
  },
  menuItem: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "12px 20px",
    color: "#bdc3c7",
    cursor: "pointer",
    transition: "all 0.3s",
    textDecoration: "none",
    fontSize: "14px",
  },
  menuItemActive: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "12px 20px",
    color: "white",
    cursor: "pointer",
    backgroundColor: "rgba(52, 152, 219, 0.3)",
    borderLeft: "3px solid #3498db",
    textDecoration: "none",
    fontSize: "14px",
  },
  footer: {
    padding: "15px 20px",
    borderTop: "1px solid rgba(255,255,255,0.1)",
    color: "#bdc3c7",
    fontSize: "13px",
  },
  footerSub: {
    fontSize: "11px",
    marginTop: "4px",
    opacity: 0.7,
  },
};
